-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 13:06:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema covid19
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema covid19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covid19` DEFAULT CHARACTER SET utf8 ;
USE `covid19` ;

-- -----------------------------------------------------
-- Table `covid19`.`continents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid19`.`continents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid19`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid19`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `population` INT NOT NULL,
  `geold` VARCHAR(5) NULL,
  `code` VARCHAR(5) NOT NULL,
  `continent_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_countries_continents_idx` (`continent_id` ASC) VISIBLE,
  CONSTRAINT `fk_countries_continents`
    FOREIGN KEY (`continent_id`)
    REFERENCES `covid19`.`continents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid19`.`deaths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid19`.`deaths` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `deaths` INT NOT NULL,
  `cases` INT NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reports_countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_reports_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `covid19`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid19`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid19`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `week` INT NOT NULL,
  `positive` INT NOT NULL,
  `done` INT NOT NULL,
  `source` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tests_countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_tests_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `covid19`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
